### ISSUE TITLE
[0.3.0] Scenes 101 ("how to basic")

### ISSUE THREAD

**Issue by puttehi** [Panakotta00/FicsIt-Cam#11]
The new update seems huge but there's no documentation on how to use it. It seems like it have affected timelapse cameras too, which I'm most interested in personally. 

How do I set up and configure a timelapse camera through the scene editor?

I have currently got this far on my own:

- `/fic create <scene_1>` 
- `/fic edit <scene_1>` 
- Created, configured (FOV) and positioned a camera in the editor: "Cam_1"

**Comment by Panakotta00** [comment]
On the SMR page i linked a over 2h video tutorial.
It will take a bit till i remake the written docs.

**Comment by puttehi** [comment]
Thanks! Missed it, will look into it... 😄 

If you can change the changelogs, perhaps put it on top of there to reduce the chance for the next user to face this issue? E.g.

"Huge update
<...>
See and learn about the changes in-depth: <video link>
<rest of the log>"

Feel free to close this issue if no relevant discussion topics come to mind.
