### ISSUE TITLE
U6 (tentative question)

### ISSUE THREAD

**Issue by mitoskalandiel** [Panakotta00/FicsIt-Cam#16]
I realize this is still early days for U6 updates, but is it going to be a "thing" for us content creators?

do you need help with anything?

hmu

**Comment by Panakotta00** [comment]
Yes... I'm right now a bit busy IRL.
A update should release soon™️ .
For now you can try the [CI builds](https://jenkins.massivebytes.net/job/FicsIt-Cam/job/development/).
You could join the [FicsIt-Networks Discord Server](https://discord.gg/3VfZ6Da) and help by reporting on any issues you have with these builds to speed-up release time.

**Comment by mitoskalandiel** [comment]
so I tried [build 29](https://jenkins.massivebytes.net/job/FicsIt-Cam/job/development/29/) (and since I "only" wanted this for timelapses) I can happily report that for me it's worked absolutely greatand I have put it through its paces in the last few hours and yeah, m8, it's great, it's working, no crashes no issues and superb picture quality
