### ISSUE TITLE
Game consistently crashes while in editor view

### ISSUE THREAD

**Issue by stardestroyer123** [Panakotta00/FicsIt-Cam#17]
The game crashes (almost every time, no exaggeration) after a few minutes in the editor view. Not on opening of the editor, a few minutes after, while editing the camera or making keyframes. 

Game version: Main game (not experimental) early access, update 5, .exe file version: 4.26.2.0
SML version: v3.3.1
Mod version: 0.3.1
[SMMDebug_2022-8-4_15-54-37.zip](https://github.com/Panakotta00/FicsIt-Cam/files/9261163/SMMDebug_2022-8-4_15-54-37.zip)

**Comment by Panakotta00** [comment]
Is it possible that the crash happens, when you exit the editor?

**Comment by stardestroyer123** [comment]
One time yes, but other times it happens while im in the editor and selecting keyframes.
