### ISSUE TITLE
Mod unusable with Polish Programmers keyboard

### ISSUE THREAD

**Issue by IO5** [Panakotta00/FicsIt-Cam#4]
Polish Programmers is a variation of QWERTY that uses "right alt"/alt gr to type polish characters like ąęłóśćżź. There are more QWERTY variants for other languages that do exactly the same. 

I mention this because that's probably the reason why right alt does absolutely nothing for me in the editor.
Can I get an alternative shortcut?

**Comment by Panakotta00** [comment]
you can change the key binding in the games control settings
