### ISSUE TITLE
Image path is not documented

### ISSUE THREAD

**Issue by puttehi** [Panakotta00/FicsIt-Cam#7]
The path images are saved to is not documented anywhere but just as "in the folder". I had to go through the Timelapse camera source to find the folder.

Perhaps the documentation should state it clearly, preferably in the first section with big letters so it cannot be missed.

**Comment by Panakotta00** [comment]
It is... its in "2. Image Sequence"

**Comment by puttehi** [comment]
I see... I even tried searching for it but couldn't find anything (and didn't feel like reading the entire documentation with focus). The ficsit.app zoom doesn't make any mods documentation very readable anyways so let's place the "blame" there. But..

..Perhaps the documentation might be subject to a bit of refactoring? Maybe it should be structured more with the end user in mind. Many users don't likely need every single feature of the mod (like I'm here only for the timelapse), so naturally those users gravitate to that section of the documentation what they need, not reading through all of it.

Something like the usual boilerplate structure might work (Format: `- Section header -- Personal notes`):

- Overview -- What is this (general info), what it does(file path here), why is it created (more general info), who is it aimed for (even more general info)
- Keybinds -- Controls should be first, unless they are editor only, then they should be under Editor section
- Getting started
  - Your first camera -- Hello world
  - Creating a timelapse -- It's a simple feature for the users, so makes sense to be on top and can introduce (reference) image sequencing
  - Making an animation -- Getting more advanced, introduce editor (?)
  - Curves
  - ...
- Advanced usage (?)
  - ...

But, at the very least, configuration/keybindings/general stuff would be better at the top, visible and impossible to miss :P.

As an extra note, can this be configured somehow? Doesn't seem like it from what I remember from looking at the source? That would be a great feature, then I could for example save directly to my server and not have to worry about moving stuff 😄 

FWIW, excellent project you have here, thanks for your contribution to the modding community ❤️

**Comment by Panakotta00** [comment]
Honestly the Docs there are actually pretty new.
I'm not good in structuring these sorts of things good, i can just dump everything I know about it.
A near rewrite of the docs has to happen anyway soon because I will release the Huge Update™️ soon and there are a lot of changes. (just have a look at the discord channel and the development branch of this repository).

The path can not be changed right now, but i have it on the planning list, at least for the scenes, I'm not sure how to make it good for the timelapse cameras.

Glad you like my work ^^
