### ISSUE TITLE
Camera details show too much (and misleading) information

### ISSUE THREAD

**Issue by puttehi** [Panakotta00/FicsIt-Cam#9]
Not sure if this is a bug in camera name generation or visualization (I suspect the latter), but when I create a Timelapse camera `abc` with `/fic timelapse create abc 1234`, the cameras name will be `abc-Timelapse`, adding an extra "Timelapse" and then doubling up on it when visualizing it with `/fic timelapse list` giving me `abc-Timelapse-Timelapse`.

When referencing this camera, you need to omit the "Timelapse" parts completely and just use the original name. The "Timelapse" suffixes shouldn't be shown to the user as it will just cause confusion.

Additionally, the decimal precision is irrelevant. `200s` is sufficient to `200.000000s`. That clutters the messages and takes away space from future ideas =)

Commands used:

```
/fic timelapse create abc 1234
/fic timelapse list
/fic timelapse start abc-Timelapse-Timelapse
/fic timelapse start abc-Timelapse
```

Output:

http://prntscr.com/qvh3fthNcm-6

Preferred usage and output:

```
/fic timelapse create abc 1234
"Timelapse-Camera 'abc' created."
/fic timelapse list
List of Timelapse-Cameras:
abc: 200s
/fic timelapse start abc
```

**Comment by Panakotta00** [comment]
This will be fixed and changed with the next update already close to release.
See the development branch.
